### PR TITLE
Removed Duplicate Code & Fixed Miners working while off

### LINKED ISSUE #131: Miners work even when toggle off
**Describe the bug**
T1 and T2 miner will continue to work if you toggle power off.

**To Reproduce**
Reproducibility:  always
1.  place down a t1 or t2 miner
2. fuel it
3. toggle power off

**Expected behavior**
Should properly stop working when toggle power?

**Rimworld (please complete the following information):**
 - Type: Bug
 - Severity: Minor

 

**Additional context**
This is properly related to update @lilwhitemouse did with making miners fueled, bug wasn't present before that one.
From issue #74 

Smoke effect WILL stop working with toggle, bug it will continue to mine, so i think it need something to check toggle?

Report comming from here:
jemes78 5 hours ago 

> Hey. A small/big problem/exploit. I don't know if it is just my game but the T2 drills continue to mine even when power is toggled off on them. They do not drain power and there is no chance of "drilling too far". They just keep spitting out resources for free. I noticed it a few days ago when coal was added.

i have tested it my self also to confirm

### PR DESCRIPTION
**Pull request by Sn1p3rr3c0n**
@lilwhitemouse I am not sure if the was a special reason why the code was duplicated. But now it should be easier to maintain.

Some comments died in the process, we can bring them back if needed.

resolves #131

### CODE REVIEW

**Comment by lilwhitemouse** [comment]
I will look at this later. One reason. For the duplication of code was speed (ticks get called a lot....once a tick). One reason was that CompRefuelable already Tick()s on its own and so doesn't need any special logic.

**Comment by lilwhitemouse** [comment]
Is the spelling German?

File: Source/ProjectRimFactory/Industry/Building_DeepQuarry.cs [hunk 1]
```diff
@@ -54,6 +54,43 @@ protected static IEnumerable<ThingDef> PossibleRockDefCandidates
             }
         }
 
+        /// <summary>
+        /// One function to handel a tick in order to remove duplicate Code and Logic
+        /// </summary>
+        /// <param name="GenRecorece">Recorce Ammount based on tick</param>
```
Comment (zymex22) [inline Source/ProjectRimFactory/Industry/Building_DeepQuarry.cs:60]: should be named FuelResource ?
