### PR TITLE
Issue172

### LINKED ISSUE #172: Items are lost if they are moved from a IO Output to the DSU (based on Output Limits)
How to reproduce:

1. Place a DSU
2. Place an IO Port and configure it as an Output
3. Setup a Output limit (example 10) and enable it
4. Setup an output item (example coal)
5. Add  the item to the DSU (example coal)
6. _a stack of 10 appears on the IO Port_

Now haul more of the item to the IO Port.
The issue will occur if it cant merge onto / cant fully merge onto an existing stack of the item.

The cause for this is that the item is not spawned.

----

A related issue is that a Pawn can haul to a IO Output Port if a limit is set that is smaller then the stack size for that item.

This should be fixable by using a Harmony Patch (as already used by the DSU)

----
**Relevant Reports from the Steam Page**

> Todokoro Vor 21 Stunden 
> - Description - PRF Digital Storage Unit is deleting my resources, and refuses to stack some items together. I've been having this problem with steel and now with prometheum fuel blocks from the Dawn of War mod.

> Spodos 14. Juni um 23:14 Uhr 
> Hi there- thanks so much for updating this mod. I found a weird behavior with items disappearing I was wondering if you could help with.
> 
> When I have an IO port set as output to a deep storage unit, pawns will haul items to the IO port instead of the DSU itself. When this happens the item count will briefly go up, but then after a few seconds the items hauled to the IO port disappear. First the count goes down in the main menu on the left, but the DSU still shows it in the item list, and then when I reconcile the DSU the item disappears from there as well. I've seen it happen with a variety of items - body parts, metals, etc.
> 
> I have some storage and stack related mods installed, so I'm wondering if that's contributing to it. LWM Deep Storage, No Default Shelf Storage, Simply Storage, Pick up and Haul, Haul to Stack, OgreStack, and Stackable Chunks - any idea?
> 
> Maybe is there a way to prevent pawns from hauling to output IO ports? Thanks again for all your hard work! Love this mod.

> zr0 16. Mai um 16:49 Uhr 
> Is anyone getting disappearing resources after setting pull limits for the wireless I/O ports? I.e I set it to 2k silver max, anything beyond that just disappears when it's supposed to be sent back to the DSU.

There might be more.

### PR DESCRIPTION
**Pull request by Sn1p3rr3c0n**
resolves #172 

while we are already here we might wanna check my comment in  `Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs` Line 119

### CODE REVIEW

File: Source/ProjectRimFactory/Storage/Building_StorageUnitIOPort.cs [hunk 1]
```diff
@@ -74,6 +75,21 @@ protected OutputSettings OutputSettings
             }
         }
 
+        //
+        public bool ForbidPawnInput {
+            get
+            {
+
+                //maybe we should cash currentItem
```
Comment (lilwhitemouse) [inline Source/ProjectRimFactory/Storage/Building_StorageUnitIOPort.cs:83]: "cache" - english spelling is insane

**Comment by lilwhitemouse** [comment]
I am a little fuzzy on what the logic is here, but everything looks good (except for a few spelling errors)

**Comment by lilwhitemouse** [comment]
Re: 
```//What appens if its full?
                if (CanStoreMoreItems)
                {
                   
                    newItem.Position = Position;
                   
 
                }
```
If it is full, the item stays in the input cell (whatever it is) and blocks any be items from going there
