### PR TITLE
Issue345

### LINKED ISSUE #345: Random? on load error in the Resource Counter
I saw it before on steam or discord.

not too sure what causes it.
this relates to #168 

```
Error in Map.FinalizeLoading(): System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <567df3e0919241ba98db88bec4c6696f>:0 
  at ProjectRimFactory.Common.HarmonyPatches.Patch_UpdateResourceCounts_AssemblerQueue.Postfix (RimWorld.ResourceCounter __instance, System.Collections.Generic.Dictionary`2[TKey,TValue] ___countedAmounts) [0x00060] in <baf2b1cb4efa43f396d66da3aa833eec>:0 
  at (wrapper dynamic-method) RimWorld.ResourceCounter.RimWorld.ResourceCounter.UpdateResourceCounts_Patch1(RimWorld.ResourceCounter)
  at (wrapper dynamic-method) Verse.Map.Verse.Map.FinalizeInit_Patch2(Verse.Map)
  at (wrapper dynamic-method) Verse.Map.Verse.Map.FinalizeLoading_Patch2(Verse.Map)
  at (wrapper dynamic-method) Verse.Game.Verse.Game.LoadGame_Patch4(Verse.Game)
Verse.Log:Verse.Log.Error_Patch2(String, Boolean)
Verse.Game:Verse.Game.LoadGame_Patch4(Game)
Verse.SavedGameLoaderNow:Verse.SavedGameLoaderNow.LoadGameFromSaveFileNow_Patch5(String)
Verse.<>c:<Start>b__1_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()
```

### PR DESCRIPTION
**Pull request by Sn1p3rr3c0n**
resolves #345 

_Note for the first Count iteration (first few ticks) after a load the counter may be off. but they should fix themselves (no idea how i could also resolve that) _
---
@zymex22 I already did some testing with it but more wont hurt. especially as this was never observed in testing.
Some hints on what i now tested (maybe you have ideas for additional tests):
_Checking if the counters are accurate & no errors logged_
- Save Which a Queue
- Save and load from that Save
- have a Queue and start a new Game
- have a Queue in one map & none in another
- have separate / different queue's in different maps
- load as save with different amounts of Queues / maps
- Destroy building with a Queue

---

@lilwhitemouse while this fix works there are some parts that I'm not really happy with.
i will highlight them for you. maybe you have some Ideas how they can be improved.

### CODE REVIEW

File: Source/ProjectRimFactory/Common/PRFGameComponent.cs [hunk 1]
```diff
@@ -80,14 +93,49 @@ public static void RegisterAssemblerQueue(IAssemblerQueue queue)
...
-                if (!Current.Game.GetComponent<PRFGameComponent>().TryAddSpecialSculpture(t)) return;
-                Log.Warning("---------added test special scuplture: " + t + " at " + t.Position);
+
+        public override void LoadedGame()
+        {
+            //Remove all entrys where the Building is not where it says it is
+            //I would prefer to call a AssemblerQueue.Clear but LoadedGame() gets called after all buildings have spawn. therfor this is not possible & i need another way to remove invalid / irelevant entrys
+            for (int i = AssemblerQueue.Count - 1; i >= 0; i--)
+            {
+                if (!AssemblerQueue[i].map.thingGrid.ThingsAt( (AssemblerQueue[i] as Building).Position).Any(t => t.ToString() == AssemblerQueue[i].ToString()))
```
Comment (Sn1p3rr3c0n) [inline Source/ProjectRimFactory/Common/PRFGameComponent.cs:103]: `t.ToString() == AssemblerQueue[i].ToString()`
there has to be a better way _(i have this in multiple spots)_

File: Source/ProjectRimFactory/Common/PRFGameComponent.cs [hunk 2]
```diff
@@ -80,14 +93,49 @@ public static void RegisterAssemblerQueue(IAssemblerQueue queue)
...
         }
-        /*
-        // A quick way to test all the scupltures available, if need be.       
-        public override void LoadedGame() {
-            base.LoadedGame();
-            foreach (var t in Current.Game.CurrentMap.spawnedThings.Where(x => x is Building_Art)) {
-                if (!Current.Game.GetComponent<PRFGameComponent>().TryAddSpecialSculpture(t)) return;
-                Log.Warning("---------added test special scuplture: " + t + " at " + t.Position);
+
+        public override void LoadedGame()
```
Comment (Sn1p3rr3c0n) [inline Source/ProjectRimFactory/Common/PRFGameComponent.cs:97]: This gets called after `SpawnSetup` therefor i cant call `AssemblerQueue.Clear`
is there something that we could use instead (called before `SpawnSetup`)

Since the data in a `GameComponent` exists until the user quits to the OS we need to clear the Queue between different saves.
something OnLoad but before SpawnSetup of individual things would be perfect _(other things could then also be simplified)_

**Comment by lilwhitemouse** [comment]
Ok will look at this this evening

File: Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs [hunk 3]
```diff
@@ -549,6 +549,35 @@ public List<Thing> GetThingQueue()
...
         }
 
+        public override void DeSpawn(DestroyMode mode = DestroyMode.Vanish)
+        {
+            for (int i = thingQueue.Count - 1; i >= 0; i--)
+            {
+                //some of the things contaned are marked as Destroyed for some reason
+                if (thingQueue[i].Destroyed) thingQueue[i].ForceSetStateToUnspawned();
+
+                PlaceThingUtility.PRFTryPlaceThing(this, thingQueue[i], this.Position, this.Map, true);
```
Comment (lilwhitemouse) [inline Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs:559]: Why do you still place something if it's destroyed?

File: Source/ProjectRimFactory/Common/HarmonyPatches/UpdateResourceCountsPatch.cs [hunk 4]
```diff
@@ -64,8 +64,10 @@ static void Postfix(ResourceCounter __instance, Dictionary<ThingDef, int> ___cou
                     //Fresh Check is from ShouldCount (maybe we can hit that via harmony/reflection somhow)
                     if (innerIfMinified.def.EverStorable(false) && !innerIfMinified.IsNotFresh())
                     {
-                        
-                        ___countedAmounts[innerIfMinified.def] += innerIfMinified.stackCount;
+                        //Causes an error otherwise #345 (seems to be clothing that causes it)
+                        if (___countedAmounts.Keys.Contains(innerIfMinified.def)){
+                            ___countedAmounts[innerIfMinified.def] += innerIfMinified.stackCount;
```
Comment (lilwhitemouse) [inline Source/ProjectRimFactory/Common/HarmonyPatches/UpdateResourceCountsPatch.cs:76]: if (___countedAmounts.ContainsKey(innerIfMinified.def)) {...}

File: Source/ProjectRimFactory/Common/HarmonyPatches/UpdateResourceCountsPatch.cs [hunk 5]
```diff
@@ -13,6 +13,7 @@ namespace ProjectRimFactory.Common.HarmonyPatches
     
     public interface IAssemblerQueue
     {
+        Map map { get; }
```
Comment (lilwhitemouse) [inline Source/ProjectRimFactory/Common/HarmonyPatches/UpdateResourceCountsPatch.cs:16]: Map Map { get; }

File: Source/ProjectRimFactory/Common/PRFGameComponent.cs (hunk 2 above)
Comment (lilwhitemouse) [reply Source/ProjectRimFactory/Common/PRFGameComponent.cs:97]: I thought GameComponents were created on a new load and only exist while a game is being played?

AssemblerQueue should be empty when first created (as I understand it) - is this not true?

Comment (lilwhitemouse) [reply Source/ProjectRimFactory/Common/PRFGameComponent.cs:97]: Oh.  Make it non-static.  There's no benefit to having it static, is there?  Accessing it quickly can be done by having a static variable that points to the actual (local) queue (that is set in the game component constructor) if you need it to be fast.

File: Source/ProjectRimFactory/Common/PRFGameComponent.cs (hunk 1 above)
Comment (lilwhitemouse) [reply Source/ProjectRimFactory/Common/PRFGameComponent.cs:103]: Actually....`ToString()` is both relatively fast (string comparisons are actually fairly fast internally?) and fairly reasonable.  Another option would be `GetHashCode()`

You might get slightly faster performance using a `HashSet` rather than a `List`, in which case....you don't care (don't need to check), because if you add the same thing to a HashSet twice...it's only in there once!

File: Source/ProjectRimFactory/Common/PRFGameComponent.cs (hunk 2 above)
Comment (lilwhitemouse) [reply Source/ProjectRimFactory/Common/PRFGameComponent.cs:97]: As I noted (in possibly another place; I don't know github that well), you can probably use a local field instead of a `static` field, and if you need fast access have a static member that points to it

Comment (Sn1p3rr3c0n) [reply Source/ProjectRimFactory/Common/PRFGameComponent.cs:97]: hmm during my tests it looked like `GameComponents` are created when game starts independent from Saves & Loads.
but i will try without static

File: Source/ProjectRimFactory/Common/PRFGameComponent.cs (hunk 1 above)
Comment (Sn1p3rr3c0n) [reply Source/ProjectRimFactory/Common/PRFGameComponent.cs:103]: OK. I expected it to be worse.

File: Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs (hunk 3 above)
Comment (Sn1p3rr3c0n) [reply Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs:559]: The Idea was that if your assembler with X items in the Queue gets destroyed by lets say:
Insects, Mortar or Gunfire then `public override void Destroy` is not called instead `DeSpawn` is called.
there all items in the Queue except the first one are `Destroyed` _(not sure why)_

I think it should drop those items instead of letting them vanish.
_(We could also let the items take damage if this is a balance concern)_

File: Source/ProjectRimFactory/Common/PRFGameComponent.cs [hunk 6]
```diff
@@ -17,19 +17,20 @@ public class PRFGameComponent : GameComponent {
...
-        public static void RegisterAssemblerQueue(IAssemblerQueue queue)
+        public void RegisterAssemblerQueue(IAssemblerQueue queue)
         {
             //enshure that there are no duplicates
             //im shure there is a better way
-            AssemblerQueue.RemoveAll(q => queue.ToString() == q.ToString());
+           // AssemblerQueue.RemoveAll(q => queue.ToString() == q.ToString());
 
             AssemblerQueue.Add(queue);
+#if DEBUG
```
Comment (lilwhitemouse) [inline Source/ProjectRimFactory/Common/PRFGameComponent.cs:27]: C# has this fancy thing where any call to `Debug.Message` will *not be compiled* unless it's a debug build! ( See `[System.Diagnostics.Conditional("DEBUG")]` in Common/Debug.cs)  So the #if DEBUG is not needed (unless you need to do any pre-calculation for the Debug.Message() call)

File: Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs (hunk 3 above)
Comment (lilwhitemouse) [reply Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs:564]: Ah; thank you!
